- name: Reset ansible_user shell to prevent failing
  become: yes
  user:
    name: "{{ ansible_ssh_user }}"
    shell: "/bin/bash"

- name: Reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection

- name: Uninstalling zsh
  make:
    target: uninstall
    chdir: "/opt/zsh-{{ zsh_local_version }}"
  become: yes

- name: Removing source folder
  file:
    path: "/opt/zsh-{{ zsh_local_version }}"
    state: absent
  become: yes